version: '3'

services:
  db:
    container_name: migrator_db
    image: mysql:5.7 # pull the mysql image with the tag 5.7 from docker hub
    env_file:
      - docker.env
    ports:
      - 3307:3306

  eloquent-migrator:
    container_name: eloquent_migrator
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db # Start the container after the db container is up
    env_file:
      - docker.env
